const { describe, it, mock } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('crypto');

/**
 * Integration-level checks for the Lifecycle → Recruitment vacancy handoff.
 * Full HTTP + DB tests can extend this with supertest + MySQL test schema.
 */
describe('Lifecycle ↔ Recruitment (integration)', () => {
  it('cloneJobPositionFromSource returns UUID and uses INSERT…SELECT with status open', async () => {
    mock.method(crypto, 'randomUUID', () => '22222222-2222-2222-2222-222222222222');

    const { cloneJobPositionFromSource } = require('../../src/services/jobVacancyClone');
    const captured = [];
    const conn = {
      async query(sql, params) {
        captured.push({ sql, params });
        return [];
      },
    };

    const newJobId = await cloneJobPositionFromSource(conn, {
      sourceJobPositionId: 'existing-role-id',
      createdByUserId: 'hr-user-id',
    });

    assert.equal(newJobId, '22222222-2222-2222-2222-222222222222');
    assert.equal(captured.length, 1);
    assert.match(captured[0].sql, /INSERT INTO JobPosition/i);
    assert.match(captured[0].sql, /\bopen\b/i);
    assert.deepEqual(captured[0].params, [newJobId, 'hr-user-id', 'existing-role-id']);

    mock.restoreAll();
  });

  it('resignation completion guard: idempotent second completion maps to conflict', () => {
    const row = { exit_acknowledged_at: null };
    function completeResignationOnce() {
      if (row.exit_acknowledged_at) {
        return { httpStatus: 409, error: 'Resignation already completed' };
      }
      row.exit_acknowledged_at = new Date().toISOString();
      return { httpStatus: 200, autoGeneratedJobPositionId: 'new-job' };
    }
    assert.equal(completeResignationOnce().httpStatus, 200);
    assert.equal(completeResignationOnce().httpStatus, 409);
  });
});
